languageCode = "en"
languageName = "English"
weight = 1
title = "V1C70R_N00B"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
   logo = "img/logo.png"
   secondaryLogo = "img/secondary-logo.png"
   description = "Welcome to the land of geeks"
#   copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "V1c70r_n00b"
   email = "victormaina2024@outlook.com"
   image = "profile.png"
   imageQuality = 96
   headline = """What if changing the world was just about being here? By showing up no matter how many times we get told we don’t belong? By staying true even when we are shamed into being false? By believing in ourselves even when we are too different? And if we all held on to that, if we refuse to budge and fall in line. if we stood our ground for long enough, just maybe the world can’t help but change around us
 
~ Elliot Alderson~


⚠️The content on this site is for educational purposes only. I do not support illegal activities or unauthorized hacking. Use responsibly and ensure you have proper permission before testing any system. You are responsible for your actions.⚠️"""
   bio = """Security Analyst || CTF player   

Philippians 4:13"""
   links = [
#      { email = "mailto:victormaina2024@outlook.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/V1c70rn00b" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://www.linkedin.com/in/victor-mwai/" },
#     { mastodon = "https://mastodon.instance/@username" },
     { medium = "https://medium.com/@V1c70r_n00b" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://x.com/v1c70r_n00b" },
     { "x-twitter" = "https://twitter.com/v1c70r_n00b" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
   ]

